[workspace]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["https://prefix.dev/conda-forge"]
name = "pytorch"
platforms = ["linux-64"]

[system-requirements]
cuda = "12.4"

[dependencies]
pytorch-gpu = "*"
ipython = "*"